<a href="https://colab.research.google.com/github/miladghavami/NEW_LERNING_PATH_FROM_SCRATCH/blob/main/learning_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/images/SN_web_lightmode.png" width="300" alt="cognitiveclass.ai logo">
</center>

<h1 align=center><font size = 5>Assignment: Notebook for Graded Assessment</font></h1>

# Introduction

Using this Python notebook you will:

1.  Understand three Chicago datasets
2.  Load the three datasets into three tables in a SQLIte database
3.  Execute SQL queries to answer assignment questions

## Understand the datasets

To complete the assignment problems in this notebook you will be using three datasets that are available on the city of Chicago's Data Portal:

1.  <a href="https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">Socioeconomic Indicators in Chicago</a>
2.  <a href="https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">Chicago Public Schools</a>
3.  <a href="https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">Chicago Crime Data</a>

### 1. Socioeconomic Indicators in Chicago

This dataset contains a selection of six socioeconomic indicators of public health significance and a “hardship index,” for each Chicago community area, for the years 2008 – 2012.

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:

[https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2](https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

### 2. Chicago Public Schools

This dataset shows all school level performance data used to create CPS School Report Cards for the 2011-2012 school year. This dataset is provided by the city of Chicago's Data Portal.

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:

[https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t](https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

### 3. Chicago Crime Data

This dataset reflects reported incidents of crime (with the exception of murders where data exists for each victim) that occurred in the City of Chicago from 2001 to present, minus the most recent seven days.

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:

[https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2](https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

### Download the datasets

This assignment requires you to have these three tables populated with a subset of the whole datasets.

In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet.

Use the links below to read the data files using the Pandas library.

* Chicago Census Data

https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCensusData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01

* Chicago Public Schools

https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoPublicSchools.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01

* Chicago Crime Data

https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCrimeData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01

**NOTE:** Ensure you use the datasets available on the links above instead of directly from the Chicago Data Portal. The versions linked here are subsets of the original datasets and have some of the column names modified to be more database friendly which will make it easier to complete this assignment.

Execute the below code cell to install the required libraries

In [ ]:
!pip install pandas
!pip install ipython-sql prettytable
import prettytable
prettytable.DEFAULT = 'DEFAULT'

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: ipython-sql in /usr/local/lib/python3.13/dist-packages (0.5.0)
Requirement already satisfied: prettytable in /usr/local/lib/python3.13/dist-packages (3.18.0)
Requirement already satisfied: ipython in /usr/local/lib/python3.13/dist-packages (from ipython-sql) (7.34.0)
Requirement already satisfied: sqlalchemy>=2.0 in /usr/local/lib/python3.13/dist-packages (from ipython-sql) (2.1.1)
Requirement already satisfied: sqlparse in /usr/local/lib/python3.13/dist-packages (from ipython-sql) (0.6.0)
Requirement already satisfied: six in /usr/local/lib/python3.13/dist-packages (from ipython-sql) (1.17.0)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.13/dist-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: wcwidth>=0.3.5 in /usr/local/lib/python3.13/dist-packages (from prettytable) (0.9.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy>=2.0->ipython-sql) (4.16.0)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.13/dist-packages (from ipython->ipython-sql) (80.10.2)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.13/dist-packages (from ipython->ipython-sql) (0.20.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.13/dist-packages (from ipython->ipython-sql) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.13/dist-packages (from ipython->ipython-sql) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.13/dist-packages (from ipython->ipython-sql) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from ipython->ipython-sql) (3.0.53)
Requirement already satisfied: pygments in /usr/local/lib/python3.13/dist-packages (from ipython->ipython-sql) (2.21.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.13/dist-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.13/dist-packages (from ipython->ipython-sql) (0.2.2)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.13/dist-packages (from ipython->ipython-sql) (4.9.0)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in /usr/local/lib/python3.13/dist-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.7)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.13/dist-packages (from pexpect>4.3->ipython->ipython-sql) (0.7.0)

### Store the datasets in database tables

To analyze the data using SQL, it first needs to be loaded into SQLite DB.
We will create three tables in as under:

1.  **CENSUS_DATA**
2.  **CHICAGO_PUBLIC_SCHOOLS**
3.  **CHICAGO_CRIME_DATA**

Load the `pandas` and `sqlite3` libraries and establish a connection to `FinalDB.db`

In [ ]:
import pandas as pd
import sqlite3

con = sqlite3.connect("FinalDB.db")

Load the SQL magic module

In [ ]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Use `Pandas` to load the data available in the links above to dataframes. Use these dataframes to load data on to the database `FinalDB.db` as required tables.

In [ ]:
from pandas.core.indexes import multi
from numpy._core.defchararray import replace
df1 = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCensusData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01.")
df1.to_sql("CENSUS_DATA", con, if_exists= "replace",  index=False, method= "multi")
df1.head(3)

,COMMUNITY_AREA_NUMBER,COMMUNITY_AREA_NAME,PERCENT_OF_HOUSING_CROWDED,PERCENT_HOUSEHOLDS_BELOW_POVERTY,PERCENT_AGED_16__UNEMPLOYED,PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA,PERCENT_AGED_UNDER_18_OR_OVER_64,PER_CAPITA_INCOME,HARDSHIP_INDEX
0,1.0,Rogers Park,7.7,23.6,8.7,18.2,27.5,23939,39.0
1,2.0,West Ridge,7.8,17.2,8.8,20.8,38.5,23040,46.0
2,3.0,Uptown,3.8,24.0,8.9,11.8,22.2,35787,20.0

In [ ]:
df2 = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoPublicSchools.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01.")
df2.to_sql("CHICAGO_PUBLIC_SCHOOLS", con, if_exists= "replace",  index=False, method= "multi")
df2.head(3)

,School_ID,NAME_OF_SCHOOL,"Elementary, Middle, or High School",Street_Address,City,State,ZIP_Code,Phone_Number,Link,Network_Manager,...,Freshman_on_Track_Rate__,X_COORDINATE,Y_COORDINATE,Latitude,Longitude,COMMUNITY_AREA_NUMBER,COMMUNITY_AREA_NAME,Ward,Police_District,Location
0,610038,Abraham Lincoln Elementary School,ES,615 W Kemper Pl,Chicago,IL,60614,(773) 534-5720,http://schoolreports.cps.edu/SchoolProgressRep...,Fullerton Elementary Network,...,NDA,1171699.458,1915829.428,41.924497,-87.644522,7,LINCOLN PARK,43,18,"(41.92449696, -87.64452163)"
1,610281,Adam Clayton Powell Paideia Community Academy ...,ES,7511 S South Shore Dr,Chicago,IL,60649,(773) 535-6650,http://schoolreports.cps.edu/SchoolProgressRep...,Skyway Elementary Network,...,NDA,1196129.985,1856209.466,41.760324,-87.556736,43,SOUTH SHORE,7,4,"(41.76032435, -87.55673627)"
2,610185,Adlai E Stevenson Elementary School,ES,8010 S Kostner Ave,Chicago,IL,60652,(773) 535-2280,http://schoolreports.cps.edu/SchoolProgressRep...,Midway Elementary Network,...,NDA,1148427.165,1851012.215,41.747111,-87.731702,70,ASHBURN,13,8,"(41.74711093, -87.73170248)"

In [ ]:
df3 = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCrimeData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01.")
df3.to_sql("CHICAGO_CRIME_DATA", con, if_exists= "replace",  index=False, method= "multi")
df3.head(10)

,ID,CASE_NUMBER,DATE,BLOCK,IUCR,PRIMARY_TYPE,DESCRIPTION,LOCATION_DESCRIPTION,ARREST,DOMESTIC,...,DISTRICT,WARD,COMMUNITY_AREA_NUMBER,FBICODE,X_COORDINATE,Y_COORDINATE,YEAR,LATITUDE,LONGITUDE,LOCATION
0,3512276,HK587712,2004-08-28,047XX S KEDZIE AVE,890,THEFT,FROM BUILDING,SMALL RETAIL STORE,False,False,...,9,14.0,58.0,6,1155838.0,1873050.0,2004,41.807440,-87.703956,"(41.8074405, -87.703955849)"
1,3406613,HK456306,2004-06-26,009XX N CENTRAL PARK AVE,820,THEFT,$500 AND UNDER,OTHER,False,False,...,11,27.0,23.0,6,1152206.0,1906127.0,2004,41.898280,-87.716406,"(41.898279962, -87.716405505)"
2,8002131,HT233595,2011-04-04,043XX S WABASH AVE,820,THEFT,$500 AND UNDER,NURSING HOME/RETIREMENT HOME,False,False,...,2,3.0,38.0,6,1177436.0,1876313.0,2011,41.815933,-87.624642,"(41.815933131, -87.624642127)"
3,7903289,HT133522,2010-12-30,083XX S KINGSTON AVE,840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,...,4,7.0,46.0,6,1194622.0,1850125.0,2010,41.743665,-87.562463,"(41.743665322, -87.562462756)"
4,10402076,HZ138551,2016-02-02,033XX W 66TH ST,820,THEFT,$500 AND UNDER,ALLEY,False,False,...,8,15.0,66.0,6,1155240.0,1860661.0,2016,41.773455,-87.706480,"(41.773455295, -87.706480471)"
5,7732712,HS540106,2010-09-29,006XX W CHICAGO AVE,810,THEFT,OVER $500,PARKING LOT/GARAGE(NON.RESID.),False,False,...,12,27.0,24.0,6,1171668.0,1905607.0,2010,41.896447,-87.644939,"(41.896446772, -87.644938678)"
6,10769475,HZ534771,2016-11-30,050XX N KEDZIE AVE,810,THEFT,OVER $500,STREET,False,False,...,17,33.0,14.0,6,1154133.0,1933314.0,2016,41.972845,-87.708600,"(41.972844913, -87.708600079)"
7,4494340,HL793243,2005-12-16,005XX E PERSHING RD,860,THEFT,RETAIL THEFT,GROCERY FOOD STORE,True,False,...,2,3.0,38.0,6,1180448.0,1879234.0,2005,41.823880,-87.613504,"(41.823879885, -87.613503857)"
8,3778925,HL149610,2005-01-28,100XX S WASHTENAW AVE,810,THEFT,OVER $500,STREET,False,False,...,22,19.0,72.0,6,1160129.0,1838040.0,2005,41.711281,-87.689179,"(41.711280513, -87.689179097)"
9,3324217,HK361551,2004-05-13,033XX W BELMONT AVE,820,THEFT,$500 AND UNDER,SMALL RETAIL STORE,False,False,...,17,35.0,21.0,6,1153590.0,1921084.0,2004,41.939296,-87.710923,"(41.939295821, -87.710923442)"

Establish a connection between SQL magic module and the database `FinalDB.db`

In [ ]:
%%sql sqlite:///FinalDB.db

You can now proceed to the the following questions. Please note that a graded assignment will follow this lab and there will be a question on each of the problems stated below. It can be from the answer you received or the code you write for this problem. Therefore, please keep a note of both your codes as well as the response you generate.

## Problems

Now write and execute SQL queries to solve assignment problems

### Problem 1

##### Find the total number of crimes recorded in the CRIME table.

In [ ]:
%%sql
SELECT *
FROM pragma_table_info('CHICAGO_CRIME_DATA');

 * sqlite:///FinalDB.db
Done.

[(0, 'ID', 'INTEGER', 0, None, 0),
 (1, 'CASE_NUMBER', 'TEXT', 0, None, 0),
 (2, 'DATE', 'TEXT', 0, None, 0),
 (3, 'BLOCK', 'TEXT', 0, None, 0),
 (4, 'IUCR', 'TEXT', 0, None, 0),
 (5, 'PRIMARY_TYPE', 'TEXT', 0, None, 0),
 (6, 'DESCRIPTION', 'TEXT', 0, None, 0),
 (7, 'LOCATION_DESCRIPTION', 'TEXT', 0, None, 0),
 (8, 'ARREST', 'INTEGER', 0, None, 0),
 (9, 'DOMESTIC', 'INTEGER', 0, None, 0),
 (10, 'BEAT', 'INTEGER', 0, None, 0),
 (11, 'DISTRICT', 'INTEGER', 0, None, 0),
 (12, 'WARD', 'REAL', 0, None, 0),
 (13, 'COMMUNITY_AREA_NUMBER', 'REAL', 0, None, 0),
 (14, 'FBICODE', 'TEXT', 0, None, 0),
 (15, 'X_COORDINATE', 'REAL', 0, None, 0),
 (16, 'Y_COORDINATE', 'REAL', 0, None, 0),
 (17, 'YEAR', 'INTEGER', 0, None, 0),
 (18, 'LATITUDE', 'REAL', 0, None, 0),
 (19, 'LONGITUDE', 'REAL', 0, None, 0),
 (20, 'LOCATION', 'TEXT', 0, None, 0)]

In [ ]:
%%sql
SELECT COUNT(*)
FROM CHICAGO_CRIME_DATA

 * sqlite:///FinalDB.db
Done.

[(533,)]

In [ ]:
RESULT = %sql SELECT COUNT(*) FROM CHICAGO_CRIME_DATA
RESULT[0][0]

 * sqlite:///FinalDB.db
Done.

533

### Problem 2

##### List community area names and numbers with per capita income less than 11000.

1. CENSUS_DATA
2. CHICAGO_PUBLIC_SCHOOLS
3. CHICAGO_CRIME_DATA

In [ ]:
%%sql
SELECT name, type
FROM pragma_table_info('CENSUS_DATA')
WHERE name LIKE '%capita%';

 * sqlite:///FinalDB.db
Done.

[('PER_CAPITA_INCOME', 'INTEGER')]

In [ ]:
%%sql
SELECT
    C.COMMUNITY_AREA_NUMBER,
    C.COMMUNITY_AREA_NAME,
    C.PER_CAPITA_INCOME
FROM CHICAGO_PUBLIC_SCHOOLS AS CH
JOIN CENSUS_DATA AS C
    ON CH.COMMUNITY_AREA_NUMBER = C.COMMUNITY_AREA_NUMBER
WHERE C.PER_CAPITA_INCOME < 11000;

 * sqlite:///FinalDB.db
Done.

[(26.0, 'West Garfield Park', 10934),
 (26.0, 'West Garfield Park', 10934),
 (26.0, 'West Garfield Park', 10934),
 (26.0, 'West Garfield Park', 10934),
 (26.0, 'West Garfield Park', 10934),
 (26.0, 'West Garfield Park', 10934),
 (26.0, 'West Garfield Park', 10934),
 (26.0, 'West Garfield Park', 10934),
 (30.0, 'South Lawndale', 10402),
 (30.0, 'South Lawndale', 10402),
 (30.0, 'South Lawndale', 10402),
 (30.0, 'South Lawndale', 10402),
 (30.0, 'South Lawndale', 10402),
 (30.0, 'South Lawndale', 10402),
 (30.0, 'South Lawndale', 10402),
 (30.0, 'South Lawndale', 10402),
 (30.0, 'South Lawndale', 10402),
 (30.0, 'South Lawndale', 10402),
 (30.0, 'South Lawndale', 10402),
 (30.0, 'South Lawndale', 10402),
 (30.0, 'South Lawndale', 10402),
 (30.0, 'South Lawndale', 10402),
 (30.0, 'South Lawndale', 10402),
 (30.0, 'South Lawndale', 10402),
 (30.0, 'South Lawndale', 10402),
 (30.0, 'South Lawndale', 10402),
 (30.0, 'South Lawndale', 10402),
 (30.0, 'South Lawndale', 10402),
 (30.0, 'South Lawndale', 10402),
 (30.0, 'South Lawndale', 10402),
 (37.0, 'Fuller Park', 10432),
 (37.0, 'Fuller Park', 10432),
 (54.0, 'Riverdale', 8201),
 (54.0, 'Riverdale', 8201),
 (54.0, 'Riverdale', 8201),
 (54.0, 'Riverdale', 8201)]

### Problem 3

##### List all case numbers for crimes involving minors?(children are not considered minors for the purposes of crime analysis)

In [ ]:
%%sql
SELECT CASE_NUMBER, DESCRIPTION
FROM CHICAGO_CRIME_DATA
WHERE DESCRIPTION LIKE '%MINOR%';

 * sqlite:///FinalDB.db
Done.

[('HL266884', 'SELL/GIVE/DEL LIQUOR TO MINOR'),
 ('HK238408', 'ILLEGAL CONSUMPTION BY MINOR')]

In [ ]:
%%sql
SELECT DISTINCT PRIMARY_TYPE, DESCRIPTION
FROM CHICAGO_CRIME_DATA

 * sqlite:///FinalDB.db
Done.

[('THEFT', 'FROM BUILDING'),
 ('THEFT', '$500 AND UNDER'),
 ('THEFT', 'FINANCIAL ID THEFT: OVER $300'),
 ('THEFT', 'OVER $500'),
 ('THEFT', 'RETAIL THEFT'),
 ('THEFT', 'AGG: FINANCIAL ID THEFT'),
 ('THEFT', 'PURSE-SNATCHING'),
 ('THEFT', 'POCKET-PICKING'),
 ('THEFT', 'ATTEMPT THEFT'),
 ('BATTERY', 'SIMPLE'),
 ('BATTERY', 'DOMESTIC BATTERY SIMPLE'),
 ('BATTERY', 'AGG PO HANDS NO/MIN INJURY'),
 ('BATTERY', 'PRO EMP HANDS NO/MIN INJURY'),
 ('BATTERY', 'AGGRAVATED:KNIFE/CUTTING INSTR'),
 ('BATTERY', 'AGGRAVATED: OTHER DANG WEAPON'),
 ('BATTERY', 'AGGRAVATED: HANDGUN'),
 ('BATTERY', 'AGGRAVATED DOMESTIC BATTERY'),
 ('BATTERY', 'AGGRAVATED DOMESTIC BATTERY: OTHER DANG WEAPON'),
 ('CRIMINAL DAMAGE', 'TO VEHICLE'),
 ('CRIMINAL DAMAGE', 'TO CITY OF CHICAGO PROPERTY'),
 ('CRIMINAL DAMAGE', 'TO PROPERTY'),
 ('CRIMINAL DAMAGE', 'CRIMINAL DEFACEMENT'),
 ('NARCOTICS', 'POSS: CANNABIS 30GMS OR LESS'),
 ('NARCOTICS', 'POSS: HEROIN(WHITE)'),
 ('NARCOTICS', 'MANU/DEL:CANNABIS 10GM OR LESS'),
 ('NARCOTICS', 'MANU/DELIVER: HEROIN (WHITE)'),
 ('NARCOTICS', 'POSS: CRACK'),
 ('NARCOTICS', 'FOUND SUSPECT NARCOTICS'),
 ('NARCOTICS', 'MANU/DELIVER: METHAMPHETAMINES'),
 ('NARCOTICS', 'POSS: COCAINE'),
 ('NARCOTICS', 'ATTEMPT POSSESSION NARCOTICS'),
 ('NARCOTICS', 'SOLICIT NARCOTICS ON PUBLICWAY'),
 ('NARCOTICS', 'MANU/DELIVER:CRACK'),
 ('OTHER OFFENSE', 'TELEPHONE THREAT'),
 ('OTHER OFFENSE', 'OBSCENE TELEPHONE CALLS'),
 ('OTHER OFFENSE', 'VIOLATE ORDER OF PROTECTION'),
 ('OTHER OFFENSE', 'HARASSMENT BY TELEPHONE'),
 ('OTHER OFFENSE', 'PROBATION VIOLATION'),
 ('OTHER OFFENSE', 'HARASSMENT BY ELECTRONIC MEANS'),
 ('OTHER OFFENSE', 'PAROLE VIOLATION'),
 ('OTHER OFFENSE', 'FALSE/STOLEN/ALTERED TRP'),
 ('OTHER OFFENSE', 'OTHER VEHICLE OFFENSE'),
 ('OTHER OFFENSE', 'OTHER CRIME AGAINST PERSON'),
 ('OTHER OFFENSE', 'SEX OFFENDER: FAIL REG NEW ADD'),
 ('ASSAULT', 'SIMPLE'),
 ('ASSAULT', 'AGGRAVATED: OTHER DANG WEAPON'),
 ('ASSAULT', 'AGGRAVATED: HANDGUN'),
 ('ASSAULT', 'AGGRAVATED PO: OTHER DANG WEAP'),
 ('ASSAULT', 'AGGRAVATED:KNIFE/CUTTING INSTR'),
 ('ASSAULT', 'PRO EMP HANDS NO/MIN INJURY'),
 ('BURGLARY', 'UNLAWFUL ENTRY'),
 ('BURGLARY', 'FORCIBLE ENTRY'),
 ('MOTOR VEHICLE THEFT', 'AUTOMOBILE'),
 ('MOTOR VEHICLE THEFT', 'THEFT/RECOVERY: AUTOMOBILE'),
 ('MOTOR VEHICLE THEFT', 'ATT: AUTOMOBILE'),
 ('MOTOR VEHICLE THEFT', 'TRUCK, BUS, MOTOR HOME'),
 ('DECEPTIVE PRACTICE', 'CREDIT CARD FRAUD'),
 ('DECEPTIVE PRACTICE', 'THEFT OF LABOR/SERVICES'),
 ('DECEPTIVE PRACTICE', 'FORGERY'),
 ('DECEPTIVE PRACTICE', 'THEFT OF LOST/MISLAID PROP'),
 ('DECEPTIVE PRACTICE', 'FRAUD OR CONFIDENCE GAME'),
 ('DECEPTIVE PRACTICE', 'THEFT BY LESSEE,MOTOR VEH'),
 ('DECEPTIVE PRACTICE', 'BOGUS CHECK'),
 ('DECEPTIVE PRACTICE', 'FINANCIAL IDENTITY THEFT OVER $ 300'),
 ('DECEPTIVE PRACTICE', 'ILLEGAL USE CASH CARD'),
 ('ROBBERY', 'ARMED: HANDGUN'),
 ('ROBBERY', 'STRONGARM - NO WEAPON'),
 ('ROBBERY', 'VEHICULAR HIJACKING'),
 ('ROBBERY', 'ARMED:KNIFE/CUTTING INSTRUMENT'),
 ('ROBBERY', 'AGGRAVATED'),
 ('ROBBERY', 'AGGRAVATED VEHICULAR HIJACKING'),
 ('CRIMINAL TRESPASS', 'TO STATE SUP LAND'),
 ('CRIMINAL TRESPASS', 'TO RESIDENCE'),
 ('CRIMINAL TRESPASS', 'TO LAND'),
 ('CRIMINAL TRESPASS', 'TO VEHICLE'),
 ('PROSTITUTION', 'CALL OPERATION'),
 ('PROSTITUTION', 'SOLICIT ON PUBLIC WAY'),
 ('PROSTITUTION', 'SOLICIT FOR BUSINESS'),
 ('WEAPONS VIOLATION', 'UNLAWFUL POSS OF HANDGUN'),
 ('WEAPONS VIOLATION', 'UNLAWFUL POSS OTHER FIREARM'),
 ('PUBLIC PEACE VIOLATION', 'RECKLESS CONDUCT'),
 ('PUBLIC PEACE VIOLATION', 'BOMB THREAT'),
 ('OFFENSE INVOLVING CHILDREN', 'AGG SEX ASSLT OF CHILD FAM MBR'),
 ('OFFENSE INVOLVING CHILDREN', 'SEX ASSLT OF CHILD BY FAM MBR'),
 ('OFFENSE INVOLVING CHILDREN', 'CRIM SEX ABUSE BY FAM MEMBER'),
 ('OFFENSE INVOLVING CHILDREN', 'AGG CRIM SEX ABUSE FAM MEMBER'),
 ('CRIM SEXUAL ASSAULT', 'ATTEMPT NON-AGGRAVATED'),
 ('CRIM SEXUAL ASSAULT', 'NON-AGGRAVATED'),
 ('CRIM SEXUAL ASSAULT', 'AGGRAVATED: HANDGUN'),
 ('SEX OFFENSE', 'AGG CRIMINAL SEXUAL ABUSE'),
 ('SEX OFFENSE', 'OTHER'),
 ('INTERFERENCE WITH PUBLIC OFFICER', 'RESIST/OBSTRUCT/DISARM OFFICER'),
 ('INTERFERENCE WITH PUBLIC OFFICER', 'ESCAPE'),
 ('GAMBLING', 'GAME/DICE'),
 ('LIQUOR LAW VIOLATION', 'SELL/GIVE/DEL LIQUOR TO MINOR'),
 ('LIQUOR LAW VIOLATION', 'ILLEGAL CONSUMPTION BY MINOR'),
 ('ARSON', 'AGGRAVATED'),
 ('ARSON', 'BY FIRE'),
 ('HOMICIDE', 'FIRST DEGREE MURDER'),
 ('KIDNAPPING', 'CHILD ABDUCTION/STRANGER'),
 ('INTIMIDATION', 'INTIMIDATION'),
 ('STALKING', 'CYBERSTALKING'),
 ('OBSCENITY', 'OBSCENE MATTER'),
 ('CONCEALED CARRY LICENSE VIOLATION', 'OTHER'),
 ('PUBLIC INDECENCY', 'LICENSED PREMISE'),
 ('NON-CRIMINAL', 'LOST PASSPORT'),
 ('OTHER NARCOTIC VIOLATION', 'INTOXICATING COMPOUNDS'),
 ('HUMAN TRAFFICKING', 'INVOLUNTARY SERVITUDE'),
 ('NON - CRIMINAL', 'FOID - REVOCATION'),
 ('RITUALISM', 'AGG RIT MUT: HANDS/FIST/FEET SERIOUS INJURY'),
 ('NON-CRIMINAL (SUBJECT SPECIFIED)', 'NOTIFICATION OF CIVIL NO CONTACT ORDER'),
 ('DOMESTIC VIOLENCE', 'DOMESTIC VIOLENCE')]

### Problem 4

##### List all kidnapping crimes involving a child?

In [ ]:
%%sql
SELECT *
FROM CHICAGO_CRIME_DATA
WHERE PRIMARY_TYPE LIKE "%kidnapping%"
AND DESCRIPTION LIKE "%CHILD%"

 * sqlite:///FinalDB.db
Done.

[(5276766, 'HN144152', '2007-01-26', '050XX W VAN BUREN ST', '1792', 'KIDNAPPING', 'CHILD ABDUCTION/STRANGER', 'STREET', 0, 0, 1533, 15, 29.0, 25.0, '20', 1143050.0, 1897546.0, 2007, 41.87490841, -87.75024931, '(41.874908413, -87.750249307)')]

### Problem 5

##### List the kind of crimes that were recorded at schools. (No repetitions)

In [ ]:
%%sql
SELECT *
FROM CHICAGO_CRIME_DATA
WHERE LOCATION_DESCRIPTION LIKE "%school%"

 * sqlite:///FinalDB.db
Done.

[(4006321, 'HL353697', '2005-05-04', '077XX S BURNHAM AVE', '460', 'BATTERY', 'SIMPLE', 'SCHOOL, PUBLIC, GROUNDS', 0, 0, 421, 4, 7.0, 43.0, '08B', 1196066.0, 1854156.0, 2005, 41.75469107, -87.55703869, '(41.754691074, -87.557038686)'),
 (4430638, 'HL725506', '2005-11-09', '048XX N FRANCISCO AVE', '484', 'BATTERY', 'PRO EMP HANDS NO/MIN INJURY', 'SCHOOL, PUBLIC, BUILDING', 1, 0, 2031, 20, 40.0, 4.0, '08B', 1156348.0, 1932071.0, 2005, 41.96938944, -87.70048881, '(41.96938944, -87.700488807)'),
 (6644618, 'HP716225', '2008-12-04', '030XX S DR MARTIN LUTHER KING JR DR', '460', 'BATTERY', 'SIMPLE', 'SCHOOL, PUBLIC, BUILDING', 0, 0, 2112, 1, 2.0, 35.0, '08B', 1179306.0, 1885032.0, 2008, 41.83981621, -87.61751617, '(41.839816207, -87.617516172)'),
 (2341955, 'HH639427', '2002-09-10', '005XX N WALLER AVE', '460', 'BATTERY', 'SIMPLE', 'SCHOOL, PUBLIC, BUILDING', 0, 0, 1512, 15, 29.0, 25.0, '08B', 1138238.0, 1903181.0, 2002, 41.89045993, -87.76778089, '(41.890459933, -87.767780886)'),
 (11110571, 'JA460432', '2017-10-05', '076XX S HOMAN AVE', '460', 'BATTERY', 'SIMPLE', 'SCHOOL, PUBLIC, GROUNDS', 0, 0, 835, 8, 18.0, 70.0, '08B', 1155024.0, 1853614.0, 2017, 41.75412154, -87.70746025, '(41.754121535, -87.707460248)'),
 (7399281, 'HS200939', '2010-03-10', '053XX W CONGRESS PKWY', '1320', 'CRIMINAL DAMAGE', 'TO VEHICLE', 'SCHOOL, PUBLIC, GROUNDS', 0, 0, 1522, 15, 29.0, 25.0, '14', 1140822.0, 1897164.0, 2010, 41.8739014, -87.7584391, '(41.873901397, -87.758439102)'),
 (3530721, 'HK577020', '2004-08-23', '016XX W JONQUIL TER', '2024', 'NARCOTICS', 'POSS: HEROIN(WHITE)', 'SCHOOL, PUBLIC, GROUNDS', 1, 0, 2422, 24, 49.0, 1.0, '18', 1163893.0, 1951001.0, 2004, 42.0211776, -87.67220843, '(42.021177601, -87.67220843)'),
 (7502426, 'HS305355', '2010-05-13', '035XX S WASHTENAW AVE', '1821', 'NARCOTICS', 'MANU/DEL:CANNABIS 10GM OR LESS', 'SCHOOL, PUBLIC, BUILDING', 1, 0, 913, 9, 12.0, 58.0, '18', 1158944.0, 1880896.0, 2010, 41.82890791, -87.69234919, '(41.828907913, -87.692349187)'),
 (8082600, 'HT315369', '2011-05-26', '032XX W ADAMS ST', '545', 'ASSAULT', 'PRO EMP HANDS NO/MIN INJURY', 'SCHOOL, PUBLIC, GROUNDS', 0, 0, 1124, 11, 28.0, 27.0, '08A', 1154752.0, 1898890.0, 2011, 41.87837031, -87.70724814, '(41.878370307, -87.707248137)'),
 (7174283, 'HR585012', '2009-10-13', '043XX W 79TH ST', '1330', 'CRIMINAL TRESPASS', 'TO LAND', 'SCHOOL, PUBLIC, GROUNDS', 1, 0, 834, 8, 13.0, 70.0, '26', 1148764.0, 1851854.0, 2009, 41.74941446, -87.7304466, '(41.749414464, -87.730446597)'),
 (2075734, 'HH292682', '2002-04-05', '016XX W BRYN MAWR AV', '2850', 'PUBLIC PEACE VIOLATION', 'BOMB THREAT', 'SCHOOL, PRIVATE, BUILDING', 0, 0, 2012, 20, None, None, '26', None, None, 2002, None, None, None),
 (1806896, 'G635735', '2001-10-22', '0000X N HERMITAGE AV', '2850', 'PUBLIC PEACE VIOLATION', 'BOMB THREAT', 'SCHOOL, PUBLIC, BUILDING', 1, 0, 1333, 12, None, None, '26', 1164687.0, 1900646.0, 2001, 41.88298425, -87.67071922, '(41.882984246, -87.670719218)')]

### Problem 6

##### List the type of schools along with the average safety score for each type.

### Problem 7

##### List 5 community areas with highest % of households below poverty line

### Problem 8

##### Which community area is most crime prone? Display the coumminty area number only.


Double-click **here** for a hint

<!--
Query for the 'community area number' that has most number of incidents
-->

### Problem 9

##### Use a sub-query to find the name of the community area with highest hardship index

### Problem 10

##### Use a sub-query to determine the Community Area Name with most number of crimes?

## Author(s)

<h4> Hima Vasudevan </h4>
<h4> Rav Ahuja </h4>
<h4> Ramesh Sannreddy </h4>

## Contribtuor(s)

<h4> Malika Singla </h4>
<h4>Abhishek Gagneja</h4>
<!--
## Change log

| Date       | Version | Changed by        | Change Description                             |
| ---------- | ------- | ----------------- | ---------------------------------------------- |
|2023-10-18  | 2.6     | Abhishek Gagneja  | Modified instruction set |
| 2022-03-04 | 2.5     | Lakshmi Holla     | Changed markdown.                   |
| 2021-05-19 | 2.4     | Lakshmi Holla     | Updated the question                           |
| 2021-04-30 | 2.3     | Malika Singla     | Updated the libraries                          |
| 2021-01-15 | 2.2     | Rav Ahuja         | Removed problem 11 and fixed changelog         |
| 2020-11-25 | 2.1     | Ramesh Sannareddy | Updated the problem statements, and datasets   |
| 2020-09-05 | 2.0     | Malika Singla     | Moved lab to course repo in GitLab             |
| 2018-07-18 | 1.0     | Rav Ahuja         | Several updates including loading instructions |
| 2018-05-04 | 0.1     | Hima Vasudevan    | Created initial version                        |
-->
## <h3 align="center"> © IBM Corporation 2023. All rights reserved. <h3/>